import {test} from 'node:test';
import assert from 'node:assert/strict';
import worker,{identityEmail} from '../src/index.js';
const env={WECHAT_APP_ID:'appid',WECHAT_APP_SECRET:'secret',SUPABASE_URL:'https://supabase.test',SUPABASE_SERVICE_ROLE_KEY:'server-secret',IDENTITY_HMAC_SECRET:'long-random-secret',LOGIN_LIMITER:{limit:async()=>({success:true})}};
test('identity email is stable, scoped by app and hides raw OpenID',async()=>{const a=await identityEmail(env,'openid');assert.equal(a,await identityEmail(env,'openid'));assert.notEqual(a,await identityEmail({...env,WECHAT_APP_ID:'other'},'openid'));assert.ok(!a.includes('openid'))});
test('missing config and rate limit fail closed',async()=>{const request=()=>new Request('https://worker.test/login',{method:'POST',body:'{"code":"code"}'});assert.equal((await worker.fetch(request(),{})).status,503);assert.equal((await worker.fetch(request(),{...env,LOGIN_LIMITER:{limit:async()=>({success:false})}})).status,429)});
test('WeChat verified login returns only client session; rejects spoofed identity',async()=>{const original=globalThis.fetch;const calls=[];globalThis.fetch=async(url,options)=>{calls.push({url:String(url),body:options?.body});const u=String(url);if(u.includes('weixin.qq.com'))return Response.json({openid:'verified-openid',session_key:'NEVER_RETURN'});if(u.includes('chob_wechat_register_session'))return Response.json(null);if(u.includes('chob_wechat_identity'))return Response.json('uid');if(u.endsWith('/admin/users/uid'))return Response.json({id:'uid',email:'existing@wechat.chob.invalid'});if(u.endsWith('/generate_link'))return Response.json({hashed_token:'hash',verification_type:'magiclink'});if(u.endsWith('/verify'))return Response.json({access_token:'header.eyJzdWIiOiJ1aWQiLCJzZXNzaW9uX2lkIjoiMDAwMDAwMDAtMDAwMC00MDAwLTgwMDAtMDAwMDAwMDAwMDEwIn0.signature',refresh_token:'refresh',expires_in:3600,user:{id:'uid',email:'private'}});throw Error('Unexpected endpoint')};try{const r=await worker.fetch(new Request('https://worker.test/login',{method:'POST',body:JSON.stringify({code:'code',openid:'attacker'})}),env);assert.equal(r.status,200);const data=await r.json();assert.deepEqual(data.user,{id:'uid'});assert.equal(data.access_token,'header.eyJzdWIiOiJ1aWQiLCJzZXNzaW9uX2lkIjoiMDAwMDAwMDAtMDAwMC00MDAwLTgwMDAtMDAwMDAwMDAwMDEwIn0.signature');assert.ok(!JSON.stringify(data).includes('NEVER_RETURN'));assert.ok(calls.some(c=>c.body?.includes('verified-openid')));assert.ok(!calls.some(c=>c.body?.includes('attacker')))}finally{globalThis.fetch=original}});
test('invalid WeChat code never contacts Supabase',async()=>{const original=globalThis.fetch;let count=0;globalThis.fetch=async()=>{count++;return Response.json({errcode:40029})};try{const r=await worker.fetch(new Request('https://worker.test/login',{method:'POST',body:'{"code":"invalid"}'}),env);assert.equal(r.status,401);assert.equal(count,1)}finally{globalThis.fetch=original}});

test('binding uses verified WeChat OpenID and Web one-time code, then registers session',async()=>{const original=globalThis.fetch,calls=[];globalThis.fetch=async(url,options)=>{const u=String(url),body=options?.body?JSON.parse(options.body):null;calls.push({u,body});if(u.includes('weixin.qq.com'))return Response.json({openid:'real-openid'});if(u.endsWith('/rpc/chob_wechat_bind')){assert.equal(body.open_id,'real-openid');assert.equal(body.link_code,'a'.repeat(64));return Response.json('uid')}if(u.endsWith('/admin/users/uid'))return Response.json({email:'existing@example.com'});if(u.endsWith('/generate_link'))return Response.json({hashed_token:'hash',verification_type:'magiclink'});if(u.endsWith('/verify'))return Response.json({access_token:'header.eyJzdWIiOiJ1aWQiLCJzZXNzaW9uX2lkIjoiMDAwMDAwMDAtMDAwMC00MDAwLTgwMDAtMDAwMDAwMDAwMDEwIn0.signature',refresh_token:'refresh',user:{id:'uid'}});if(u.endsWith('/rpc/chob_wechat_register_session'))return Response.json(null);throw Error('Unexpected')};try{const r=await worker.fetch(new Request('https://worker.test/bind',{method:'POST',body:JSON.stringify({code:'wx',link_code:'a'.repeat(64),openid:'fake',user_id:'fake'})}),env);assert.equal(r.status,200);assert.ok(calls.some(c=>c.u.endsWith('/chob_wechat_register_session')&&c.body.linked_user==='uid'));assert.equal(calls.filter(c=>c.u.endsWith('/chob_wechat_identity')).length,0)}finally{globalThis.fetch=original}});
test('session registration failure returns no credentials',async()=>{const original=globalThis.fetch;globalThis.fetch=async url=>{const u=String(url);if(u.includes('weixin.qq.com'))return Response.json({openid:'openid'});if(u.endsWith('/chob_wechat_identity'))return Response.json('uid');if(u.endsWith('/admin/users/uid'))return Response.json({email:'e@example.com'});if(u.endsWith('/generate_link'))return Response.json({hashed_token:'h',verification_type:'magiclink'});if(u.endsWith('/verify'))return Response.json({access_token:'header.eyJzdWIiOiJ1aWQiLCJzZXNzaW9uX2lkIjoiMDAwMDAwMDAtMDAwMC00MDAwLTgwMDAtMDAwMDAwMDAwMDEwIn0.signature',refresh_token:'secret',user:{id:'uid'}});return Response.json({error:'failed'},{status:403})};try{const r=await worker.fetch(new Request('https://worker.test/login',{method:'POST',body:'{"code":"wx"}'}),env);assert.equal(r.status,502);assert.equal((await r.json()).access_token,undefined)}finally{globalThis.fetch=original}});

test('new WeChat identity creates one mapped UUID and registers its mini session',async()=>{const original=globalThis.fetch,calls=[];const jwt='h.'+Buffer.from(JSON.stringify({sub:'new-user',session_id:'00000000-0000-4000-8000-000000000020'})).toString('base64url')+'.s';globalThis.fetch=async(url,options)=>{const u=String(url),body=options?.body?JSON.parse(options.body):null;calls.push({u,body});if(u.includes('weixin.qq.com'))return Response.json({openid:'new-openid'});if(u.endsWith('/chob_wechat_identity'))return Response.json(body.linked_user||null);if(u.endsWith('/generate_link')){assert.match(body.email,/^wx-[a-f0-9]{64}@wechat.chob.invalid$/);return Response.json({hashed_token:'h',verification_type:'magiclink'})}if(u.endsWith('/verify'))return Response.json({access_token:jwt,refresh_token:'r',expires_in:3600,user:{id:'new-user'}});if(u.endsWith('/chob_wechat_register_session'))return Response.json(null);throw Error('Unexpected endpoint')};try{const r=await worker.fetch(new Request('https://worker.test/login',{method:'POST',body:'{"code":"wx"}'}),env);assert.equal(r.status,200);assert.deepEqual((await r.json()).user,{id:'new-user'});assert.equal(calls.filter(c=>c.u.endsWith('/chob_wechat_identity')&&c.body.linked_user==='new-user').length,1);assert.ok(calls.some(c=>c.u.endsWith('/chob_wechat_register_session')&&c.body.linked_user==='new-user'))}finally{globalThis.fetch=original}});
