<script setup>
import {ref,onMounted} from 'vue';
import {allRows,rpc} from '@/lib/api';
const rows=ref([]),error=ref(''),busy=ref(false),replies=ref({});
async function load(){try{rows.value=(await allRows('chob_submission_reviews')).filter(r=>r.status==='pending');error.value=''}catch(e){error.value=e.message}}
async function review(item,decision){if(busy.value)return;if(!window.confirm(decision==='approved'?'确认通过并公开这份投稿及关联事项？':'确认拒绝这份投稿？'))return;busy.value=true;try{await rpc('chob_review_submission',{target:item.id,decision,response:replies.value[item.id]||''});await load()}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(load);
</script>
<template><section class="space-y-4"><p v-if="error" class="text-red-700">{{error}}</p><button class="btn-secondary" @click="load">刷新投稿</button><p v-if="!rows.length">没有待审核投稿。</p><article v-for="item in rows" :key="item.id" class="card space-y-3"><h2 class="text-lg font-bold">{{item.payload.activity}}</h2><p>{{item.payload.date}} · {{item.payload.region}} · {{item.payload.city}} · {{item.payload.venue}}</p><p>艺人：{{item.payload.unmatched_artist || item.payload.artist_selections?.join(' / ') || item.payload.artist_ids?.join(' / ')}}</p><p>当地时间：{{item.payload.time}} · 活动分类：{{item.payload.type}} · 参与方式：{{item.payload.participation_condition}}</p><p class="whitespace-pre-wrap">{{item.payload.note}}</p><details><summary>完整投稿内容（含艺人 ID、购票 URL、具体事项）</summary><pre class="whitespace-pre-wrap break-all">{{JSON.stringify(item.payload,null,2)}}</pre></details><div class="flex flex-wrap gap-3"><a v-for="url in item.payload.images" :key="url" :href="url" target="_blank" rel="noopener noreferrer"><img :src="url" alt="投稿活动图片" style="max-width:180px;max-height:240px;object-fit:contain"/></a></div><router-link :to="'/events'" class="underline">在活动管理中核对 / 修改草稿（{{item.event_id}}）</router-link><textarea v-model="replies[item.id]" class="input-field" maxlength="4000" placeholder="审核回复 / 拒绝原因"/><div class="flex gap-3"><button :disabled="busy" class="btn-primary" @click="review(item,'approved')">通过并公开</button><button :disabled="busy" class="btn-secondary" @click="review(item,'rejected')">拒绝</button></div></article></section></template>
