import { defineStore } from 'pinia'
import { ref, computed } from 'vue'
const messages = {
  zh: {
    scheduleTotal: '共{n}项日程',
    eventTotal: '共{n}个活动',
    dateLabel: '日期',
    broadcast: '直播',
    loadingImage: '图片加载中…',
    choose: '请选择',
    cancel: '取消',
    submit: '提交',
    leaveDraft: '内容尚未保存，是否放弃并删除草稿？',
    discard: '放弃草稿',
    keepEditing: '继续填写',
    participation: '参与方式',
    buy: '立即购票',
    info: '详情',
    from: '查看原文',
    participationInfo: '参与信息',
    companyHelp: '可输入公司名；没有合适选项时，可在备注补充。',
    dayActivities: '全天活动',
    enlarge: '点击放大图片',
    zoom: '放大或还原图片',
    imageFailed: '图片加载失败，可切换其他图片',
    theme: '外观',
    light: '日间',
    dark: '夜间',
    artistName: '艺人名称',
    region: '地区',
    activityName: '活动名称',
    entryKind: '内容',
    eventType: '活动类型',
    startDate: '开始日期',
    endDate: '结束日期',
    startTime: '开始时间',
    endTime: '结束时间',
    venueLabel: '场地',
    cityLabel: '城市／线上直播',
    cityHint: '城市名，或填写“线上直播”',
    priceLabel: '价格',
    saleDate: '售票日期',
    saleTime: '售票时间',
    imageHint: '每行一条公开图片链接，最多 9 张',
    noteLabel: '备注',
    entryDraftNote:
      '新增活动表单预览。目前仅能在本机保存草稿，尚未开放提交，不会写入表格或发布到网站。',
    saveDraft: '存草稿',
    submitLater: '提交暂未开放',
    draftSaved: '草稿已保存在此浏览器，尚未提交。',
    draftFailed: '草稿未保存，请检查浏览器是否允许本地存储。',
    dateOrder: '结束日期不能早于开始日期。',
    calendar: '日历',
    task: '事项',
    month: '月',
    week: '周',
    company: '公司',
    category: '类型',
    all: '全部',
    offline: '线下',
    online: '线上',
    search: '搜索艺人、活动、城市…',
    today: '今天',
    synced: '已同步',
    loading: '同步中',
    unconfigured: '未连接',
    error: '同步失败',
    stale: '离线缓存',
    demo: '演示数据',
    retry: '重新同步',
    preview: '查看演示',
    connect: '尚未连接日程数据',
    connectNote: '日程数据源接通后，活动会显示在这里。你也可以先查看三种视图的演示。',
    demoNote: '当前展示虚构演示数据，仅用于预览样式。',
    errorNote: '暂时无法获取最新日程，请稍后重试。',
    staleNote: '暂时无法获取最新数据，正在显示上次缓存。',
    noEvents: '这一天，留一点空白。',
    emptyNote: '暂无符合筛选条件的日程',
    reset: '重置筛选',
    more: '还有 {n} 项',
    dayDetail: '当天日程',
    close: '关闭',
    official: '官方发布',
    fan: '粉丝分享',
    favorite: '收藏',
    saved: '已收藏',
    favorites: '我的收藏',
    localFavorites: '收藏保存在当前浏览器，暂不跨设备同步。',
    private: '非公开',
    tba: '待公布',
    allDay: '全天',
    location: '地点',
    start: '开始',
    end: '结束',
    contact: '联系渠道',
    link: '查看活动 / 前往购票',
    noLink: '暂无公开链接',
    brand: '站台活动',
    series: '剧集宣传',
    stage: '舞台演出',
    other: '其他',
    ticket: '抢票',
    support: '应援',
    booking: '订桌',
    purchase: '购买',
    form: '填表',
    add: '新增活动',
    entryLater: '录入网站筹备中',
    about: '关于 CHOB',
    aboutText:
      '把喜欢的人，放进日历里。CHOB 收集泰国艺人在泰国、中国与海外的行程，也记录每一个值得留意的抢票、订桌和报名时刻。',
    aboutNote: '星标描边代表官方发布，实心标签代表粉丝分享。活动以主办方最新公布为准。',
    entryNote:
      '本期为日程展示端。独立录入网站将在后续接入，普通用户、管理员和公司账号的权限由服务端管理。',
    updated: '上次更新',
    dayCount: '项日程',
    monthCount: '本月日程',
    clear: '清除',
    bl: '泰腐',
    gl: '泰百',
    band: '乐队',
    singer: '歌手',
    group: '男女团',
    actor: '演员',
    music: '音乐',
    time: '时间',
    note: '备注',
    images: '活动图片',
    previous: '上一张',
    next: '下一张',
    monthPrev: '上个月',
    monthNext: '下个月',
    weekPrev: '上一周',
    weekNext: '下一周',
    filterActive: '筛选中',
    detail: '活动详情',
  },
  en: {
    scheduleTotal: '{n} scheduled events',
    eventTotal: '{n} events',
    dateLabel: 'Date',
    broadcast: 'Broadcast',
    loadingImage: 'Loading image…',
    choose: 'Select',
    cancel: 'Cancel',
    submit: 'Submit',
    leaveDraft: 'Discard your changes and delete this draft?',
    discard: 'Discard draft',
    keepEditing: 'Keep editing',
    participation: 'Participation',
    buy: 'Buy tickets',
    info: 'Details',
    from: 'Original post',
    participationInfo: 'Participation details',
    companyHelp: 'Type a company name or add details in the notes.',
    dayActivities: 'Daily events',
    enlarge: 'Enlarge image',
    zoom: 'Zoom in or out',
    imageFailed: 'Image unavailable. Try another image.',
    theme: 'Appearance',
    light: 'Light',
    dark: 'Dark',
    artistName: 'Artist name',
    region: 'Region',
    activityName: 'Activity name',
    entryKind: 'Content',
    eventType: 'Activity type',
    startDate: 'Start date',
    endDate: 'End date',
    startTime: 'Start time',
    endTime: 'End time',
    venueLabel: 'Venue',
    cityLabel: 'City / online',
    cityHint: 'City name, or 线上直播 for online',
    priceLabel: 'Price',
    saleDate: 'Ticket date',
    saleTime: 'Ticket time',
    imageHint: 'One public image URL per line, up to 9 images',
    noteLabel: 'Notes',
    entryDraftNote:
      'Form preview. Save drafts in this browser only. Submission is not open; nothing is sent to the sheet or published.',
    saveDraft: 'Save local draft',
    submitLater: 'Submission coming later',
    draftSaved: 'Draft saved in this browser. Not submitted.',
    draftFailed: 'Could not save. Check browser storage permissions.',
    dateOrder: 'End date must not precede start date.',
    calendar: 'Calendar',
    task: 'To-dos',
    month: 'Month',
    week: 'Week',
    company: 'Company',
    category: 'Type',
    all: 'All',
    offline: 'In person',
    online: 'Online',
    search: 'Search artists, events, cities…',
    today: 'Today',
    synced: 'Synced',
    loading: 'Syncing',
    unconfigured: 'Not connected',
    error: 'Sync failed',
    stale: 'Cached data',
    demo: 'Demo data',
    retry: 'Retry sync',
    preview: 'Explore demo',
    connect: 'Your calendar is waiting',
    connectNote:
      'Events will appear when the data source is connected. Explore the three views with fictional preview data.',
    demoNote: 'Fictional preview data. These are not real schedules.',
    errorNote: 'Latest schedules are unavailable. Please try again.',
    staleNote: 'Showing the last saved data. Updates are temporarily unavailable.',
    noEvents: 'A little room in your day.',
    emptyNote: 'No schedules match these filters.',
    reset: 'Reset filters',
    more: '{n} more',
    dayDetail: 'Daily schedule',
    close: 'Close',
    official: 'Official',
    fan: 'Fan shared',
    favorite: 'Save',
    saved: 'Saved',
    favorites: 'Saved events',
    localFavorites: 'Saved in this browser. Cross-device sync is not available yet.',
    private: 'Private',
    tba: 'To be announced',
    allDay: 'All day',
    location: 'Location',
    start: 'Start',
    end: 'End',
    contact: 'Contact',
    link: 'Event / tickets',
    noLink: 'No public link',
    brand: 'Brand events',
    series: 'Series promotion',
    stage: 'Live performances',
    other: 'Other',
    ticket: 'Tickets',
    support: 'Fan support',
    booking: 'Reservations',
    purchase: 'Purchase',
    form: 'Registration',
    add: 'Add event',
    entryLater: 'Submissions coming later',
    about: 'About CHOB',
    aboutText:
      'Keep the people you love on your calendar. Discover Thai artists in Thailand, China and overseas, with ticket sales, reservations and registration dates in one place.',
    aboutNote:
      'Outlined stars identify official entries; solid labels identify fan contributions. Refer to the organizer for final details.',
    entryNote:
      'This release is the public calendar. A separate submission site with server-managed user, admin and company permissions will follow.',
    updated: 'Last updated',
    dayCount: 'events',
    monthCount: 'This month',
    clear: 'Clear',
    bl: 'BL',
    gl: 'GL',
    band: 'Band',
    singer: 'Singer',
    group: 'Group',
    actor: 'Actor',
    music: 'Music',
    time: 'Time',
    note: 'Notes',
    images: 'Event images',
    previous: 'Previous image',
    next: 'Next image',
    monthPrev: 'Previous month',
    monthNext: 'Next month',
    weekPrev: 'Previous week',
    weekNext: 'Next week',
    filterActive: 'Filtered',
    detail: 'Event details',
  },
  th: {
    scheduleTotal: 'กำหนดการทั้งหมด {n} รายการ',
    eventTotal: 'ทั้งหมด {n} กิจกรรม',
    dateLabel: 'วันที่',
    broadcast: 'ถ่ายทอดสด',
    loadingImage: 'กำลังโหลดรูป…',
    choose: 'เลือก',
    cancel: 'ยกเลิก',
    submit: 'ส่ง',
    leaveDraft: 'ละทิ้งการแก้ไขและลบฉบับร่างหรือไม่?',
    discard: 'ลบฉบับร่าง',
    keepEditing: 'แก้ไขต่อ',
    participation: 'การเข้าร่วม',
    buy: 'ซื้อบัตร',
    info: 'รายละเอียด',
    from: 'โพสต์ต้นฉบับ',
    participationInfo: 'ข้อมูลการเข้าร่วม',
    companyHelp: 'พิมพ์ชื่อบริษัทหรือเพิ่มข้อมูลในหมายเหตุ',
    dayActivities: 'กิจกรรมทั้งวัน',
    enlarge: 'ขยายรูปภาพ',
    zoom: 'ขยายหรือย่อรูปภาพ',
    imageFailed: 'โหลดรูปภาพไม่สำเร็จ ลองรูปอื่น',
    theme: 'ธีม',
    light: 'กลางวัน',
    dark: 'กลางคืน',
    artistName: 'ชื่อศิลปิน',
    region: 'ภูมิภาค',
    activityName: 'ชื่อกิจกรรม',
    entryKind: 'เนื้อหา',
    eventType: 'ประเภทกิจกรรม',
    startDate: 'วันที่เริ่ม',
    endDate: 'วันที่สิ้นสุด',
    startTime: 'เวลาเริ่ม',
    endTime: 'เวลาสิ้นสุด',
    venueLabel: 'สถานที่',
    cityLabel: 'เมือง / ออนไลน์',
    cityHint: 'ชื่อเมือง หรือ 线上直播 สำหรับออนไลน์',
    priceLabel: 'ราคา',
    saleDate: 'วันที่ขายบัตร',
    saleTime: 'เวลาขายบัตร',
    imageHint: 'ลิงก์รูปภาพสาธารณะหนึ่งลิงก์ต่อบรรทัด สูงสุด 9 รูป',
    noteLabel: 'หมายเหตุ',
    entryDraftNote:
      'แบบฟอร์มตัวอย่าง บันทึกฉบับร่างในเบราว์เซอร์นี้เท่านั้น ยังไม่ส่งข้อมูลไปยังตารางหรือเผยแพร่',
    saveDraft: 'บันทึกฉบับร่าง',
    submitLater: 'ยังไม่เปิดให้ส่ง',
    draftSaved: 'บันทึกฉบับร่างแล้ว ยังไม่ได้ส่ง',
    draftFailed: 'บันทึกไม่สำเร็จ โปรดตรวจสอบสิทธิ์พื้นที่จัดเก็บ',
    dateOrder: 'วันที่สิ้นสุดต้องไม่ก่อนวันที่เริ่ม',
    calendar: 'ปฏิทิน',
    task: 'รายการ',
    month: 'เดือน',
    week: 'สัปดาห์',
    company: 'บริษัท',
    category: 'ประเภท',
    all: 'ทั้งหมด',
    offline: 'ออฟไลน์',
    online: 'ออนไลน์',
    search: 'ค้นหาศิลปิน กิจกรรม เมือง…',
    today: 'วันนี้',
    synced: 'ซิงค์แล้ว',
    loading: 'กำลังซิงค์',
    unconfigured: 'ยังไม่เชื่อมต่อ',
    error: 'ซิงค์ไม่สำเร็จ',
    stale: 'ข้อมูลแคช',
    demo: 'ข้อมูลตัวอย่าง',
    retry: 'ลองซิงค์อีกครั้ง',
    preview: 'ดูตัวอย่าง',
    connect: 'ปฏิทินรอข้อมูลอยู่',
    connectNote: 'กิจกรรมจะแสดงเมื่อเชื่อมต่อแหล่งข้อมูลแล้ว สามารถดูตัวอย่างทั้งสามมุมมองได้',
    demoNote: 'ข้อมูลสมมติสำหรับดูตัวอย่างเท่านั้น ไม่ใช่กำหนดการจริง',
    errorNote: 'ไม่สามารถโหลดกำหนดการล่าสุดได้ โปรดลองอีกครั้ง',
    staleNote: 'กำลังแสดงข้อมูลที่บันทึกไว้ล่าสุด',
    noEvents: 'วันนี้ยังมีเวลาว่าง',
    emptyNote: 'ไม่พบกิจกรรมที่ตรงกับตัวกรอง',
    reset: 'ล้างตัวกรอง',
    more: 'อีก {n} รายการ',
    dayDetail: 'กำหนดการประจำวัน',
    close: 'ปิด',
    official: 'ทางการ',
    fan: 'แฟนคลับแชร์',
    favorite: 'บันทึก',
    saved: 'บันทึกแล้ว',
    favorites: 'รายการที่บันทึก',
    localFavorites: 'บันทึกในเบราว์เซอร์นี้ ยังไม่ซิงค์ข้ามอุปกรณ์',
    private: 'ไม่เปิดเผย',
    tba: 'รอประกาศ',
    allDay: 'ทั้งวัน',
    location: 'สถานที่',
    start: 'เริ่ม',
    end: 'สิ้นสุด',
    contact: 'ช่องทางติดต่อ',
    link: 'รายละเอียด / ซื้อบัตร',
    noLink: 'ยังไม่มีลิงก์',
    brand: 'งานแบรนด์',
    series: 'โปรโมตซีรีส์',
    stage: 'การแสดง',
    other: 'อื่น ๆ',
    ticket: 'ซื้อบัตร',
    support: 'ซัพพอร์ต',
    booking: 'จองโต๊ะ',
    purchase: 'ซื้อสินค้า',
    form: 'ลงทะเบียน',
    add: 'เพิ่มกิจกรรม',
    entryLater: 'ระบบเพิ่มข้อมูลกำลังพัฒนา',
    about: 'เกี่ยวกับ CHOB',
    aboutText:
      'เก็บคนที่คุณชอบไว้ในปฏิทิน รวมกำหนดการศิลปินไทยในประเทศไทย จีน และต่างประเทศ พร้อมวันขายบัตร จองโต๊ะ และลงทะเบียน',
    aboutNote:
      'กรอบพร้อมดาวคือข้อมูลทางการ ป้ายสีทึบคือข้อมูลจากแฟนค���ับ โปรดตรวจสอบรายละเอียดล่าสุดจากผู้จัดงาน',
    entryNote: 'รุ่นนี้เป็นเว็บไซต์แสดงกำหนดการ ระบบเพิ่มข้อมูลและจัดการสิทธิ์จะตามมาในภายหลัง',
    updated: 'อัปเดตล่าสุด',
    dayCount: 'กิจกรรม',
    monthCount: 'เดือนนี้',
    clear: 'ล้าง',
    bl: 'BL',
    gl: 'GL',
    band: 'วงดนตรี',
    singer: 'นักร้อง',
    group: 'ศิลปินกลุ่ม',
    actor: 'นักแสดง',
    music: 'ดนตรี',
    time: 'เวลา',
    note: 'หมายเหตุ',
    images: 'รูปกิจกรรม',
    previous: 'รูปก่อนหน้า',
    next: 'รูปถัดไป',
    monthPrev: 'เดือนก่อน',
    monthNext: 'เดือนถัดไป',
    weekPrev: 'สัปดาห์ก่อน',
    weekNext: 'สัปดาห์ถัดไป',
    filterActive: 'ใช้ตัวกรอง',
    detail: 'รายละเอียดกิจกรรม',
  },
}
export const useLanguageStore = defineStore('language', () => {
  const currentLanguage = ref('zh')
  try {
    const v = localStorage.getItem('chob-language')
    if (messages[v]) currentLanguage.value = v
  } catch {}
  const locale = computed(() => ({ zh: 'zh-CN', en: 'en-GB', th: 'th-TH' })[currentLanguage.value])
  const t = computed(() => messages[currentLanguage.value])
  function setLanguage(v) {
    if (!messages[v]) return
    currentLanguage.value = v
    document.documentElement.lang = v
    try {
      localStorage.setItem('chob-language', v)
    } catch {}
  }
  setLanguage(currentLanguage.value)
  return { currentLanguage, locale, t, setLanguage }
})
