const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const client=path.resolve(__dirname,'../client');
function setup(){const storage={},requests=[],wx={getStorageSync:k=>storage[k],setStorageSync:(k,v)=>storage[k]=v,removeStorageSync:k=>delete storage[k],request:o=>requests.push(o),login:o=>o.success({code:'wx-code'}),navigateTo:o=>{wx.route=o.url}};const module={exports:{}};vm.runInNewContext(fs.readFileSync(client+'/lib/api.js','utf8'),{module,require:()=>({supabaseUrl:'https://db',publishableKey:'public',workerUrl:'https://worker'}),wx,Date,console});return {api:module.exports,wx,requests,storage}}
const old={access_token:'old',refresh_token:'refresh',expires_at:1,user:{id:'user'}};
const fresh={access_token:'fresh',refresh_token:'next',expires_in:3600,user:{id:'user'}};
test('refresh coalesces and retains user UUID',async()=>{const {api,requests}=setup();api.save(old);const a=api.token(),b=api.token();assert.equal(requests.length,1);requests[0].success({statusCode:200,data:fresh});assert.deepEqual(await Promise.all([a,b]),['fresh','fresh']);assert.equal(api.session().user.id,'user');assert.equal(api.session().refresh_token,'next')});
test('logout during refresh cannot revive a session',async()=>{const {api,requests}=setup();api.save(old);const pending=api.token();api.save(null);requests[0].success({statusCode:200,data:fresh});await assert.rejects(pending,/请先登录/);assert.equal(api.session(),null)});
test('logout during native login cannot restore credentials',async()=>{const {api,requests}=setup();const pending=api.login();await Promise.resolve();api.save(null);requests[0].success({statusCode:200,data:fresh});await assert.rejects(pending,/请先登录/);assert.equal(api.session(),null)});
test('expired refresh clears state; transient network errors preserve it',async()=>{const {api,requests}=setup();api.save(old);let p=api.token();requests[0].fail(Error('offline'));await assert.rejects(p,/offline/);assert.ok(api.session());p=api.token();requests[1].success({statusCode:400,data:{error:'expired'}});await assert.rejects(p,/expired/);assert.equal(api.session(),null)});
test('logout revokes only the current Auth session and clears local data immediately',async()=>{const {api,requests}=setup();api.save(fresh);const p=api.logout();assert.equal(api.session(),null);assert.ok(requests[0].url.endsWith('/chob_wechat_logout'));assert.ok(requests[1].url.endsWith('/logout?scope=local'));for(const r of requests)r.success({statusCode:200,data:null});await p});
test('authenticated requests reject stale responses after logout',async()=>{const {api,requests}=setup();api.save(fresh);const p=api.rpc('chob_mini_toggle_favorite',{},true);await Promise.resolve();api.save(null);requests[0].success({statusCode:200,data:true});await assert.rejects(p,/请先登录/)});
test('unauthorized API response clears session and points back to originating action',async()=>{const {api,requests,wx}=setup();api.save(fresh);const p=api.rows('chob_personal','select=favorites');await Promise.resolve();requests[0].success({statusCode:401,data:{message:'expired'}});await assert.rejects(p,/expired/);assert.equal(api.session(),null);api.requireLogin('favorite');assert.equal(wx.route,'/pages/account/index?action=favorite')});
test('correction decodes the real unique ID before RPC; login returns once to original action',async()=>{const id='supabase:00000000-0000-4000-8000-000000000002';let page,args,back=0;const previous={};const api={session:()=>({user:{id:'user'}}),token:async()=> 'token',rpc:async(n,a)=>{args={n,a}},login:async()=>({user:{id:'user'}})};const wx={navigateBack(){back++}};const load=(name)=>{vm.runInNewContext(fs.readFileSync(client+'/pages/'+name+'/index.js','utf8'),{Page:p=>page=p,require:p=>p.endsWith('/api')?api:p.endsWith('/i18n')?{current:()=>({})}:{},wx,getCurrentPages:()=>[previous,page]});page.data=structuredClone(page.data);page.setData=d=>Object.assign(page.data,d);return page};const correction=load('correction');correction.onLoad({id:encodeURIComponent(id)});correction.data.content='Fix';correction.data.source='https://source.test';await correction.submit();assert.equal(args.n,'chob_report_correction');assert.equal(args.a.target,id.slice(9));assert.equal(correction.data.done,true);const account=load('account');account.onLoad({action:'favorite'});await account.login();assert.equal(back,1);assert.equal(previous.pendingLoginAction,'favorite');assert.equal(account.action,'')});
test('normal refresh does not invalidate an existing request from the same session',async()=>{const {api,requests,storage}=setup();api.save(fresh);const reading=api.rows('chob_personal','select=favorites');await Promise.resolve();storage['chob-session'].expires_at=1;const refreshing=api.token();requests[1].success({statusCode:200,data:fresh});await refreshing;requests[0].success({statusCode:200,data:[]});assert.deepEqual(await reading,[])});